-- 1. USERS Table
CREATE TABLE users (
    id VARCHAR(128) PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL, 
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. FRIDGES Table
CREATE TABLE fridges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL,
    owner_id VARCHAR(128) NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. FRIDGE_MEMBERS Table
CREATE TABLE fridge_members (
    fridge_id UUID NOT NULL REFERENCES fridges(id) ON DELETE CASCADE,
    user_id VARCHAR(128) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER', 
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (fridge_id, user_id)
);

-- 4. FRIDGE_INVITATIONS Table
CREATE TABLE fridge_invitations (
    inviter_id VARCHAR(128) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    invitee_id VARCHAR(128) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fridge_id UUID NOT NULL REFERENCES fridges(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (inviter_id, invitee_id, fridge_id)
);